### ISSUE TITLE
This is AMAZING!!

### ISSUE THREAD

**Issue by davidseth** [Baste-RainGames/AnimationPlayer#1]
@Baste-RainGames I am starting to wrap my head around this and just got my first 1D blend tree working with my own code. WOW! 

Thank you so much for putting this together. I have a lot to learn from your API and will continue to dig in over the next few days.

I'm happy to collaborate where possible. I'm newer to the whole Playables system but trying to get up to speed as soon as I can.

**Comment by Baste-RainGames** [comment]
Hey, thanks!

Note that the repo is very WIP - there's stuff that definitely doesn't
work. It might also be necessary to change things around such that old
data breaks.
Once I get time to get it to a higher standard of quality, I'll
advertise it here and there to get some more feedback, and hopefully
some help. At that point I'll also be much more careful with data
changes, and at least try very hard to preserve backwards compatibility.
If there's any feedback, feel free to either email me or post an issue
on the repository. If you feel like contributing, the things I want to
get done are in Assets/Docs/ATTODO.txt.
--
  Baste Buanes
  baste@rain-games.com



On Tue, Jan 2, 2018, at 5:19 PM, David Peterson wrote:
> @Baste-RainGames[1] I am starting to wrap my head around this and just
> got my first 1D blend tree working with my own code. WOW!> Thank you so much for putting this together. I have a lot to learn
> from your API and will continue to dig in over the next few days.> I'm happy to collaborate where possible. I'm newer to the whole
> Playables system but trying to get up to speed as soon as I can.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/baste-raingames
  2. https://github.com/Baste-RainGames/AnimationPlayer/issues/1
