### ISSUE TITLE
IK and animation layers

### ISSUE THREAD

**Issue by davidseth** [Baste-RainGames/AnimationPlayer#4]
@Baste-RainGames I was reading your code in AnimationPlayer.cs around line 26 regarding IK. I'm working on some IK animations and need IK passthrough but it isn't working with your system. For my beta code I've just switched to a base AnimatorContoller and it's fine for testing.

You mention two potential solutions, the second one looks interesting. Can you provide some more thoughts on how to progress with "2: Ship AnimationPlayer with an AnimatorController that's set up correctly..." ?

Cheers,

David

**Comment by Baste-RainGames** [comment]
Hi!

Right, I should've written down how to do that! Add an Animator to the same object as the AnimationPlayer, and give it an AnimatorController with no states, and IK pass turned on on it's base layer. Then all of the IK methods of the AnimationPlayer should work.
