### ISSUE TITLE
Dynamically built states on startup?

### ISSUE THREAD

**Issue by rgvox** [Baste-RainGames/AnimationPlayer#6]
I wrote a pretty awful interface admittedly and spiked some runtime creation of AnimationState into this.  My interface is a bit awful because it's so simple and relies heavily on the outsider (me) but basically It's IStateAdder and must implement an AddStates(AnimationPlayer ap) function.  I spiked it at about line 57 of AnimationPlayer.cs kinda like:

----new code:
IStateAdder[] adders = GetComponents<IStateAdder>();
            if (adders != null && adders.Length > 0)
            {
                foreach (var adder in adders)
                    adder.AddStates(this);
            }

----your existing code below: I had to create my states before the below loop fired, or else the underlying lists and stuff would be out of sync with the states.
            for (var i = 0; i < layers.Length; i++)
                layers[i].InitializeSelf(graph);

This way, I can create a component of my own and define how to add states outside of the animator.  OBVIOUSLY, there is a much cleaner approach to be taken here, but I think something like this would be hugely valuable on your API.  My AddStates() implementation basically specifies a hard-coded layer, and wipes all states from that layer to start off.  I then add in a custom number of states as needed.  This allows me to essentially define a series of animation behaviors somewhere else, and the same animator/character prefab/etc. is reusable between scenes and stuff.  In my use case, I'm creating an Idle state, a Blocking state, and n # of attacking states which are just SingleClipState in my use case.

Now that I'm done, I have 4 separate animated behaviors all created at runtime, each can have a different number of attacks and all animations are working great!  Also, if I really wanted to I could do fully randomize an infinite number of behaviors.

**Comment by Baste-RainGames** [comment]
I'll get around to making a way to add states at arbitrary times. I think it should look like this;

`var state = new SingleClipState();
state.clip = myClip;
state.name = "Woo"
int layer = 2;
animationPlayer.AddState(state, layer)
//then you can:
animationPlayer.Play("Woo", layer);`

The API also needs to allow you to set a state as the layer's default state, and to add entire layers. 

The biggest issue is the seperation between methods that needs to be called only internally and methods that you can use. You probably don't ever need access to the state's CreatePlayable, nor the AnimationPlayer's InitializeSelf. Looks like I'll need to start using the internal access modifier more, but figuring out where the line goes between making the API clean and making the API flexible will be interesting. I don't want to be as restrictive as Unity is.

**Comment by Baste-RainGames** [comment]
AnimationPlayer.AddState is now implemented. It needs a proper set of examples, but you essentially create any of the AnimationState subclasses through the appropriate Create methods (like SingleClip.Create), and call AddState. 

Adding transitions should be implemented at one point, as that has the same issues as adding states with regards to cached information.
