### ISSUE TITLE
AnimationPlayer out of sync with Editor (Can't save or edit)

### ISSUE THREAD

**Issue by rgvox** [Baste-RainGames/AnimationPlayer#7]
I'm not sure how I got into this state, but when I start up my game, the AnimationPlayer has the layers and states that I have configured through the Inspector window.  However, they don't match what is in the editor, and I think it has something to do with collisions between state names, somehow.  Anyways, it seems to fail when I attempt to ctrl+s and it also has created some weird behavior when I run the game.  Luckily, this is the layer that I'm blanking out on startup so it's not causing problems, but if it was a different, more important layer I'd be super stuck.

**Comment by Baste-RainGames** [comment]
Two states can get the same name, and then everything will break. The editor gets really confused about which state you're editing. That's probably what you're running into.

If you could send an AnimationPlayer that shows the issue, as a .unitypackage or something, that'd help me fix it. If you need to fix it on your end, you can use debug mode for the inspector to rename the states.

**Comment by rgvox** [comment]
I'm not sure I fully understand the fix here (to use debug mode.)  I will try to see if I can figure out how to send the unity package.  What jumps to mind would be check and error if the updated state name matches an already existing state, then simply rename it and maybe throw up a warning that you did so?

**Comment by rgvox** [comment]
Oh! I figured it out.  I've never used the "bind to unity" feature in VS option and didn't realize I could bind and then trigger editor breakpoints :)

**Comment by Baste-RainGames** [comment]
That wasn't what I meant at all with debug mode! But great that you figured out that you can attach to the editor, it's really usefull!

I meant selecting debug here:
![debugmode](https://user-images.githubusercontent.com/12800067/37821149-2320c7c2-2e83-11e8-8a9e-bc85c660495a.png)

So you can edit the data like this:
![inspector_edit](https://user-images.githubusercontent.com/12800067/37821197-4bc740fc-2e83-11e8-813c-b6617928b0f3.png)

That allows for editing any script without any custom inspector getting in the way. 


For the proper solution, I'm not quite sure. I update the name every time you write a character, so I can't jump in and give the user an error immediately, as they might have attack1 and want to write "attack12" or something like that.
I wish Unity had a delayed input field that actually works.
